# Generated by Django 4.2.4 on 2023-09-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AddField(
            model_name='mailingsettings',
            name='clients',
            field=models.ManyToManyField(to='mailing.client', verbose_name='Клиенты'),
        ),
        migrations.DeleteModel(
            name='MailingClient',
        ),
    ]
